In this notebook, I learned how to calculate gradients using the autograd package in PyTorch : the meaning behind required_grad paramter, what a computational graph is, how to stop autograd from tracking history and finally how to empty (zero) gradients

## Part 2 : Gradient Calculation With Autograd

In [1]:
import torch

In [2]:
x= torch.rand(3, requires_grad= True) #This is necessary when we want to calculate the gradient of a tensor.
print(x)

tensor([0.2495, 0.1581, 0.9390], requires_grad=True)


In [3]:
y= x+2
print(y)

tensor([2.2495, 2.1581, 2.9390], grad_fn=<AddBackward0>)


In [4]:
z= y*y*2
print(z)

tensor([10.1206,  9.3150, 17.2754], grad_fn=<MulBackward0>)


In [5]:
z= z.mean()
print(z)

tensor(12.2370, grad_fn=<MeanBackward0>)


In [6]:
z.backward() #dz/dx
print(x.grad)

tensor([2.9994, 2.8775, 3.9187])


The attribute .grad() is None by default and becomes a Tensor the first time a call to backward() computes gradients for self. The attribute will then contain the gradients computed and future calls to backward() will accumulate (add) gradients into it.

Now, this is how to stop pytorch from tracking the history in our computational graph.

In [7]:
x.requires_grad_(False)
print(x)

tensor([0.2495, 0.1581, 0.9390])


In [8]:
y= x.detach()
print(y)

tensor([0.2495, 0.1581, 0.9390])


In [10]:
with torch.no_grad():
    y= x+2
    print(y)

tensor([2.2495, 2.1581, 2.9390])


In [12]:
weights= torch.ones(4, requires_grad=True)

for epoch in range (3):
    
    model_output= (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
