In this notebook, I learned how to create tensors in many different ways, how to use them in basic operations(+,-,*,/), how to slice, reshape a tensor and finally how to create a numpy array from a tensor and vice versa.

##  Part 1 : Tensors basics

In [1]:
import torch

In [2]:
x = torch.empty(1) #Returns a tensor filled with uninitialized data. 
#The shape of the tensor is defined by the variable argument size.
print(x) #we haven't initialised the value yet, hence the NAN value. 1 is the size of the tensor.

tensor([nan])


In [8]:
x = torch.empty(3)
print(x) #In this case, it's like a 1D vector with 3 elements.

tensor([0.0000e+00, 9.5367e-06, 0.0000e+00])


In [6]:
x = torch.empty(2,3) #2D vector with 3 elements
print(x)

tensor([[-3., -2., -1.],
        [ 0.,  1.,  2.]])


In [10]:
x= torch.rand(2,2) #Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)
print(x)

tensor([[0.8131, 0.3307],
        [0.7931, 0.2083]])


In [12]:
x= torch.zeros(3,2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [13]:
x= torch.ones(2,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
#We can change the data type : 
x= torch.ones(1,3,dtype= torch.int)
print(x.dtype)

torch.int32


In [15]:
x= torch.ones(1,3,dtype= torch.double)
print(x.dtype)

torch.float64


In [16]:
#But by default it's torch.float32
x=torch.ones(2,3)
print(x.dtype)

torch.float32


In [17]:
#To check the size : 
x= torch.ones(1,3,dtype= torch.int)
print(x.size())

torch.Size([1, 3])


In [18]:
#We can create a tensor from existing data 
x=torch.tensor([1,2.5])
print(x)

tensor([1.0000, 2.5000])


In [19]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)

tensor([[0.7293, 0.7934],
        [0.6034, 0.5647]])


In [20]:
print(y)

tensor([[0.5411, 0.6599],
        [0.7594, 0.9032]])


In [21]:
z=x+y
print(z) #This does element wise addition 

tensor([[1.2704, 1.4533],
        [1.3628, 1.4679]])


In [22]:
z=torch.add(x,y)
print(z)

tensor([[1.2704, 1.4533],
        [1.3628, 1.4679]])


In [23]:
y.add_(x)
print(y)

tensor([[1.2704, 1.4533],
        [1.3628, 1.4679]])


In [29]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)

tensor([[0.5997, 0.6521],
        [0.4717, 0.2739]])


In [30]:
print(y)

tensor([[0.6356, 0.3418],
        [0.4445, 0.8727]])


In [31]:
z= x-y
z= torch.sub(x,y)
print(z)

tensor([[-0.0358,  0.3103],
        [ 0.0272, -0.5987]])


In [32]:
x.sub_(y)
print(x)

tensor([[-0.0358,  0.3103],
        [ 0.0272, -0.5987]])


In [33]:
#same logic for multiplication (element wise)
#z= x*y
#z= torch.mul(x,y)
#x.mul_(y)

In [34]:
#same logic for division (element wise)
#z= x/y
#z= torch.div(x,y)
#x.div(y)

These basic operations are very similar to numpy arrays.

In [35]:
x= torch.rand(5,3)
print(x)

tensor([[0.5339, 0.8474, 0.5498],
        [0.6787, 0.8244, 0.3716],
        [0.0861, 0.9911, 0.5133],
        [0.0640, 0.8295, 0.3106],
        [0.4529, 0.8551, 0.8298]])


In [37]:
print(x[:,0]) #Slincing (all rows of the first column)

tensor([0.5339, 0.6787, 0.0861, 0.0640, 0.4529])


In [39]:
print(x[1,1].item()) #One value

0.8244356513023376


In [40]:
print(x[1,1])

tensor(0.8244)


In [42]:
#Reshaping a tensor 
x= torch.rand(4,4)
print(x)

tensor([[0.9212, 0.0061, 0.1037, 0.4014],
        [0.8458, 0.8800, 0.9707, 0.4086],
        [0.9652, 0.0763, 0.2643, 0.0545],
        [0.3850, 0.5618, 0.9900, 0.6850]])


In [43]:
y=x.view(16)
print(y)

tensor([0.9212, 0.0061, 0.1037, 0.4014, 0.8458, 0.8800, 0.9707, 0.4086, 0.9652,
        0.0763, 0.2643, 0.0545, 0.3850, 0.5618, 0.9900, 0.6850])


In [45]:
y=x.view(-1,8)
print(y)

tensor([[0.9212, 0.0061, 0.1037, 0.4014, 0.8458, 0.8800, 0.9707, 0.4086],
        [0.9652, 0.0763, 0.2643, 0.0545, 0.3850, 0.5618, 0.9900, 0.6850]])


In [48]:
#Converting from numpy to a torch tensor
import numpy as np
a= torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [50]:
b= a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [51]:
print(type(b))

<class 'numpy.ndarray'>


Here, we have to be careful if the tensor is on the CPU and not the GPU because then both objects will share
the same memory location so this means that if we change one we will also change the other.

In [54]:
a.add_(1)
print(a)

tensor([3., 3., 3., 3., 3.])


In [55]:
print(b)

[3. 3. 3. 3. 3.]


the value of b also changed and that is because both a and b point to the same memory location.

In [56]:
a= np.ones(4)
print(a)

[1. 1. 1. 1.]


In [59]:
b= torch.from_numpy(a)
print(b) #We can also modify the data type.

tensor([1., 1., 1., 1.], dtype=torch.float64)


In [60]:
a+= 1
print(a)

[2. 2. 2. 2.]


In [61]:
print(b)

tensor([2., 2., 2., 2.], dtype=torch.float64)
